### ISSUE TITLE
Using Caddy on non standard ports 8080/8443

### ISSUE THREAD

**Issue by phamaralbr** [caddy-dns/duckdns#14]
Hello! My isp blocks ports 80/443, so I'm trying to do a reverse proxy with ports 8008/8443 but I can't get it to work.

I'm using this DuckDNS module so I can have a DNS Challenge and avoid using the standard ports.

If anyone has an idea on what could I do, here's what I've currently got:

**Docker Compose:**
```
services:
  caddy:
    image: serfriz/caddy-duckdns:latest
    restart: unless-stopped
    ports:
      - "8008:80"
      - "8443:443"

    environment:
      - DUCKDNS_TOKEN=REDACTED
    volumes:      
      - /home/data/config/caddy/data:/data
      - /home/data/config/caddy/config:/config
      - /home/data/config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/data/config/caddy/log:/var/log
      - /home/data/config/caddy/site:/srv
    networks:
      - caddy

networks:
  caddy:
    external: true
```

**Caddyfile**
```
mydomain.duckdns.org {
    reverse_proxy jellyfin:8096

    tls {
        dns duckdns {env.DUCKDNS_TOKEN}
    }
}
```

I've done the port forwarding on my router, and with port checker I can confirm these ports are open:
8008:8008
8443:8443

But I still can't get a connection. When accessing mydomain.duckdns.org:8443 I get:
> The connection has timed out
> The server at mydomain.duckdns.org is taking too long to respond.
